import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import { padding } from '@mui/system'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Code Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
      <main className={styles.main}>

        <style jsx>{`
            p{
              font-size:19px;
            }
            
          `}
        </style>
        <h1 className={styles.title}>
        Code Hunt
        </h1>

        <div className={styles.imageWraper}>
          <Image className={styles.homeImg} src="/images/home.avif" width={570} height={280}></Image>
        </div>

        <p className={styles.description}>
          A Blog for hunting coders by a Hunting Coder
          
        </p>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>
              How to learn Javascript in 2022?
            </h3>
            <p>
              Javascript is a language to design web page
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3>
              How to learn Javascript in 2022?
            </h3>
            <p>
              Javascript is a language to design web page
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3>
              How to learn Javascript in 2022?
            </h3>
            <p>
              Javascript is a language to design web page
            </p>
          </div>
        </div>

        
      </main>

      <footer className={styles.footer}>
        
          Powered by <b> Code Hunt</b> 
      <style jsx>{`b{
        padding:10px;
      }`}</style>
          
      </footer>
    </div>
  )
}
